[phases.setup]
nixPkgs = ['nodejs_20', 'npm']

[phases.install]
dependsOn = ['setup']
cmds = ['npm ci --omit=dev']

[phases.build]
dependsOn = ['install']
cmds = ['npm run build']

[start]
cmd = 'npm run start:prod'

[variables]
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'
NPM_CONFIG_OMIT = 'dev'
