# Simple Railway nixpacks configuration - alternative approach
[variables]
NODE_ENV = "production"

# Explicitly override Railway's default npm settings
NPM_CONFIG_PRODUCTION = ""
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"

[phases.install]
cmds = ["npm ci --omit=dev"]

[phases.build] 
cmds = ["npm run build"]

[start]
cmd = "npm run start:prod"
